// <auto-generated />
using System;
using EntArtes.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntArtes.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509212932_AddSecurityStampSync")]
    partial class AddSecurityStampSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntArtes.Core.Entities.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EncarregadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EncarregadoId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.DisponibilidadeProfessor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<bool>("Recorrente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("DisponibilidadesProfessores");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Emprestimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFimPrevisto")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxaAplicada")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("Emprestimos");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Estudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estudios");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.EstudioModalidade", b =>
                {
                    b.Property<int>("EstudioId")
                        .HasColumnType("int");

                    b.Property<int>("ModalidadeId")
                        .HasColumnType("int");

                    b.HasKey("EstudioId", "ModalidadeId");

                    b.HasIndex("ModalidadeId");

                    b.ToTable("EstudioModalidades");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<bool>("Paga")
                        .HasColumnType("bit");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("Faturas");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContribuidorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataSubmissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("EstadoConservacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PrecoVenda")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxaSimbolica")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContribuidorId");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Modalidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Modalidades");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Participante", b =>
                {
                    b.Property<int>("SessaoId")
                        .HasColumnType("int");

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.HasKey("SessaoId", "AlunoId");

                    b.HasIndex("AlunoId");

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.ProfessorModalidade", b =>
                {
                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("ModalidadeId")
                        .HasColumnType("int");

                    b.HasKey("ProfessorId", "ModalidadeId");

                    b.HasIndex("ModalidadeId");

                    b.ToTable("ProfessorModalidades");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Sessao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EncConfirmado")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("EstudioId")
                        .HasColumnType("int");

                    b.Property<int?>("FaturaId")
                        .HasColumnType("int");

                    b.Property<int>("Formato")
                        .HasColumnType("int");

                    b.Property<int>("ModalidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ProfConfirmado")
                        .HasColumnType("bit");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudioId");

                    b.HasIndex("FaturaId");

                    b.HasIndex("ModalidadeId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Sessoes");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Aluno", b =>
                {
                    b.HasOne("EntArtes.Core.Entities.Utilizador", "Encarregado")
                        .WithMany("Alunos")
                        .HasForeignKey("EncarregadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Encarregado");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.DisponibilidadeProfessor", b =>
                {
                    b.HasOne("EntArtes.Core.Entities.Utilizador", "Professor")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Emprestimo", b =>
                {
                    b.HasOne("EntArtes.Core.Entities.Item", "Item")
                        .WithMany("Emprestimos")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntArtes.Core.Entities.Utilizador", "Utilizador")
                        .WithMany("Emprestimos")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.EstudioModalidade", b =>
                {
                    b.HasOne("EntArtes.Core.Entities.Estudio", "Estudio")
                        .WithMany("ModalidadesCompativeis")
                        .HasForeignKey("EstudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntArtes.Core.Entities.Modalidade", "Modalidade")
                        .WithMany("EstudiosCompativeis")
                        .HasForeignKey("ModalidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudio");

                    b.Navigation("Modalidade");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Fatura", b =>
                {
                    b.HasOne("EntArtes.Core.Entities.Utilizador", "Utilizador")
                        .WithMany("Faturas")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Item", b =>
                {
                    b.HasOne("EntArtes.Core.Entities.Utilizador", "Contribuidor")
                        .WithMany("ItensContribuidos")
                        .HasForeignKey("ContribuidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contribuidor");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Participante", b =>
                {
                    b.HasOne("EntArtes.Core.Entities.Aluno", "Aluno")
                        .WithMany("Participacoes")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntArtes.Core.Entities.Sessao", "Sessao")
                        .WithMany("Participantes")
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.ProfessorModalidade", b =>
                {
                    b.HasOne("EntArtes.Core.Entities.Modalidade", "Modalidade")
                        .WithMany("ProfessoresHabilitados")
                        .HasForeignKey("ModalidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntArtes.Core.Entities.Utilizador", "Professor")
                        .WithMany("ProfessorModalidades")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modalidade");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Sessao", b =>
                {
                    b.HasOne("EntArtes.Core.Entities.Estudio", "Estudio")
                        .WithMany("Sessoes")
                        .HasForeignKey("EstudioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EntArtes.Core.Entities.Fatura", "Fatura")
                        .WithMany("Sessoes")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntArtes.Core.Entities.Modalidade", "Modalidade")
                        .WithMany("Sessoes")
                        .HasForeignKey("ModalidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EntArtes.Core.Entities.Utilizador", "Professor")
                        .WithMany("SessoesLecionadas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudio");

                    b.Navigation("Fatura");

                    b.Navigation("Modalidade");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Venda", b =>
                {
                    b.HasOne("EntArtes.Core.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EntArtes.Core.Entities.Utilizador", "Comprador")
                        .WithMany()
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Aluno", b =>
                {
                    b.Navigation("Participacoes");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Estudio", b =>
                {
                    b.Navigation("ModalidadesCompativeis");

                    b.Navigation("Sessoes");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Fatura", b =>
                {
                    b.Navigation("Sessoes");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Item", b =>
                {
                    b.Navigation("Emprestimos");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Modalidade", b =>
                {
                    b.Navigation("EstudiosCompativeis");

                    b.Navigation("ProfessoresHabilitados");

                    b.Navigation("Sessoes");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Sessao", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("EntArtes.Core.Entities.Utilizador", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Disponibilidades");

                    b.Navigation("Emprestimos");

                    b.Navigation("Faturas");

                    b.Navigation("ItensContribuidos");

                    b.Navigation("ProfessorModalidades");

                    b.Navigation("SessoesLecionadas");
                });
#pragma warning restore 612, 618
        }
    }
}
